name       : pyyaml
version    : 5.4.1
release    : 14
source     :
    - https://pypi.io/packages/source/P/PyYAML/PyYAML-5.4.1.tar.gz : 607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e
license    : MIT
component  : programming.python
summary    : Python YAML binding
description: |
    YAML is a data serialization format designed for human readability and interaction with scripting languages.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(yaml-0.1)
    - cython
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
