name       : pyyaml
version    : 3.11
release    : 3
source     :
    - http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz : c36c938a872e5ff494938b33b14aaa156cb439ec67548fcab3535bb78b0846e8
license    : MIT
component  : programming.python
summary    : Python YAML binding
description: |
    YAML is a data serialization format designed for human readability and interaction with scripting languages.
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(yaml-0.1)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
