name       : pyyaml
version    : 3.11
release    : 1
source     :
    - http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz : c36c938a872e5ff494938b33b14aaa156cb439ec67548fcab3535bb78b0846e8
license    : MIT
summary    : Pyython YAML binding
description: |
    YAML is a data serialization format designed for human readability and interaction with scripting languages.
    
    PyYAML is a YAML parser and emitter for the Python programming language.
    
    PyYAML features
    
    a complete  YAML 1.1 parser. In particular, PyYAML can parse all examples from the specification. The parsing algorithm is simple enough to be a reference for YAML parser implementors.
    Unicode support including UTF-8/UTF-16 input/output and \u escape sequences.
    low-level event-based parser and emitter API (like SAX).
    high-level API for serializing and deserializing native Python objects (like DOM or pickle).
    support for all types from the  YAML types repository. A simple extension API is provided.
    both pure-Python and fast LibYAML-based parsers and emitters.
    relatively sensible error messages.
setup      : |
    # Fix ypkg to not require setup..
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
