name       : pyyaml
version    : '3.12'
release    : 8
source     :
    - https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz : 592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab
license    : MIT
component  : programming.python
summary    : Python YAML binding
description: |
    YAML is a data serialization format designed for human readability and interaction with scripting languages.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(yaml-0.1)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
