name       : pyyaml
version    : 5.1.2
release    : 11
source     :
    - https://pypi.python.org/packages/source/P/PyYAML/PyYAML-5.1.2.tar.gz : 01adf0b6c6f61bd11af6e10ca52b7d4057dd0be0343eb9283c878cf3af56aee4
license    : MIT
component  : programming.python
summary    : Python YAML binding
description: |
    YAML is a data serialization format designed for human readability and interaction with scripting languages.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(yaml-0.1)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
